### ISSUE TITLE
No Delete, Save PDF to Server?

### ISSUE THREAD

**Issue by firedrow** [nonsalant/contract#12]
Could this be modified easily to not delete the contract, then save or email the resulting PDF to the server/contact?

I have an idea for user training and doing completion sign-offs.

**Comment by nonsalant** [comment]
The PDF is generated by a 3rd party service (the contract just has a button that takes to it), so this could get more complicated because you'd have to recreate the PDF-generating functionality on your own server to save it there (though not impossible, there are PDF libraries for PHP out there).

Re not deleting the contract script, this part of the code may help (it's around the top part of the scrip):

// If the filename is (or starts with) "test" or "demo" the PHP file won't delete itself, nor will it redirect to the HTML contract (when one exists)
if ( substr($fileName,0,4) == 'test' || substr($fileName,0,4) == 'demo' ) { $selfDelete = 0; }
else { $selfDelete = 1; }
