### ISSUE TITLE
FTP Generate 

### ISSUE THREAD

**Issue by bobbypanchal** [nonsalant/contract#13]
Hi, 

When i try and generate a new contract using the link provided in the readme, clicking the download contact button causes a 'Oops! That page can’t be found.' error.

Seems to be the download.php file cant be found. 

It this something that can be fixed?

Also has the code for the generate contract been shared? 

Thanks 

Bobby.

**Comment by nonsalant** [comment]
Try it again, should work now.

The source code for the Generator (e.g: http://vileworks.com/contract/generator.php ) is not currently public. (It has been, was taken out of the repo a while ago due to security concerns, and a new version -- where you generate the PHP file client side, using JavaScript -- is almost ready and should be coming out sometime in the future.)

**Comment by nonsalant** [comment]
> Do you still plan on releasing the generator code?

Still planning on releasing the client side generator, but it was pushed back quite a bit on the list of priorities so this may only happen later this year.

**Comment by stefciu** [comment]
Great. I'm looking forward also for generator code

**Comment by thephilluk** [comment]
Hi,
Any updates on the generator?
Thanks,
Philip

**Comment by nonsalant** [comment]
Sorry, it’s a lot later than I would have hoped (I had to stop work in 2020 and then started from scratch this year).

But the new Javascript-based generator is now available: the code is in the [generator folder](https://github.com/nonsalant/contract/tree/master/generator) in this repo (see the readme file in that folder for info related to the generator specifically) and it can be [used online here](https://stefanmatei.com/contract-generator/edit) to generate a PHP file.
